# Generated by Django 5.2.1 on 2025-06-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_create_post_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
